package com.tms.business.mapper;

import com.tms.business.domain.CustomNotice;
import org.springframework.stereotype.Repository;

@Repository
public interface CustomNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    int insert(CustomNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    int insertSelective(CustomNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    CustomNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    int updateByPrimaryKeySelective(CustomNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_notice
     *
     * @mbggenerated Thu Oct 05 22:37:47 CST 2017
     */
    int updateByPrimaryKey(CustomNotice record);

    CustomNotice getCustomNotice();

}