package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.FeedBack;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public interface FeedBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    int insert(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    int insertSelective(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    FeedBack selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    int updateByPrimaryKeySelective(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    int updateByPrimaryKey(FeedBack record);

    Page<FeedBack> selectList(@Param("content") String content, @Param("startTime") Date startTime, @Param("endTime") Date endTime, @Param("type") Integer type);

}