package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.HomePageModule;
import org.springframework.stereotype.Repository;

@Repository
public interface HomePageModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    int insert(HomePageModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    int insertSelective(HomePageModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    HomePageModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    int updateByPrimaryKeySelective(HomePageModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_module
     *
     * @mbggenerated Sun Oct 01 23:29:40 CST 2017
     */
    int updateByPrimaryKey(HomePageModule record);

    Page<HomePageModule> selectList(HomePageModule homePageModule);
}