package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.LiveShow;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public interface LiveShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int insert(LiveShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int insertSelective(LiveShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    LiveShow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int updateByPrimaryKeySelective(LiveShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LiveShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:12:30 CST 2017
     */
    int updateByPrimaryKey(LiveShow record);

    Page<LiveShow> selectList(@Param("name") String name, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

}