package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.ScenicSpot;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ScenicSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int insert(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int insertSelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    ScenicSpot selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int updateByPrimaryKeySelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int updateByPrimaryKey(ScenicSpot record);

    Page<ScenicSpot> selectList(ScenicSpot scenicSpot);

    ScenicSpot selectByIdAndFlagDelete(@Param("id") String id, @Param("flagDelete") Integer flagDelete);

}