package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.ScenicSpotResource;
import org.springframework.stereotype.Repository;

@Repository
public interface ScenicSpotResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int insert(ScenicSpotResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int insertSelective(ScenicSpotResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    ScenicSpotResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int updateByPrimaryKeySelective(ScenicSpotResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot_resource
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    int updateByPrimaryKey(ScenicSpotResource record);

    Page<ScenicSpotResource> selectListByDataId(String dataId);

    void deleteResourceByDataId(String dataId);
}