package com.tms.business.mapper;

import com.tms.business.domain.TbLog;
import org.springframework.stereotype.Repository;

@Repository
public interface TbLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    int insert(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    int insertSelective(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    TbLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    int updateByPrimaryKeySelective(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    int updateByPrimaryKey(TbLog record);
}