package com.tms.business.mapper;

import com.tms.business.domain.TmsLegend;
import org.springframework.stereotype.Repository;

@Repository
public interface TmsLegendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int insert(TmsLegend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int insertSelective(TmsLegend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    TmsLegend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int updateByPrimaryKeySelective(TmsLegend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int updateByPrimaryKey(TmsLegend record);

    TmsLegend getTmsLegend();
}