package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.FeedBack;
import com.tms.business.domain.TmsLegendActivity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public interface TmsLegendActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int insert(TmsLegendActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int insertSelective(TmsLegendActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    TmsLegendActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int updateByPrimaryKeySelective(TmsLegendActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TmsLegendActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_legend_activity
     *
     * @mbggenerated Sat Oct 07 10:09:54 CST 2017
     */
    int updateByPrimaryKey(TmsLegendActivity record);

    Page<TmsLegendActivity> selectList(@Param("name") String name, @Param("startTime") Date startTime, @Param("endTime") Date endTime);


}