package com.tms.business.mapper;

import com.github.pagehelper.Page;
import com.tms.business.domain.VoiceManage;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface VoiceManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int insert(VoiceManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int insertSelective(VoiceManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    VoiceManage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int updateByPrimaryKeySelective(VoiceManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(VoiceManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 15:49:57 CST 2017
     */
    int updateByPrimaryKey(VoiceManage record);

    Page<VoiceManage> selectList(@Param("name") String name);

}