package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class FeedBack implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.open_id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.nick_name
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.type
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.content
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.phone
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.create_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.modify_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.flag_delete
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.id
     *
     * @return the value of feed_back.id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.id
     *
     * @param id the value for feed_back.id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.open_id
     *
     * @return the value of feed_back.open_id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.open_id
     *
     * @param openId the value for feed_back.open_id
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.nick_name
     *
     * @return the value of feed_back.nick_name
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.nick_name
     *
     * @param nickName the value for feed_back.nick_name
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.type
     *
     * @return the value of feed_back.type
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.type
     *
     * @param type the value for feed_back.type
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.content
     *
     * @return the value of feed_back.content
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.content
     *
     * @param content the value for feed_back.content
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.phone
     *
     * @return the value of feed_back.phone
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.phone
     *
     * @param phone the value for feed_back.phone
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.create_time
     *
     * @return the value of feed_back.create_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.create_time
     *
     * @param createTime the value for feed_back.create_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.modify_time
     *
     * @return the value of feed_back.modify_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.modify_time
     *
     * @param modifyTime the value for feed_back.modify_time
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.flag_delete
     *
     * @return the value of feed_back.flag_delete
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.flag_delete
     *
     * @param flagDelete the value for feed_back.flag_delete
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FeedBack other = (FeedBack) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_back
     *
     * @mbggenerated Fri Oct 06 16:14:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}