package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class LiveShow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.id
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.name
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.image_url
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.start_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.end_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.content
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.create_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.modify_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.flag_delete
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_show.detail
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.id
     *
     * @return the value of live_show.id
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.id
     *
     * @param id the value for live_show.id
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.name
     *
     * @return the value of live_show.name
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.name
     *
     * @param name the value for live_show.name
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.image_url
     *
     * @return the value of live_show.image_url
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.image_url
     *
     * @param imageUrl the value for live_show.image_url
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.start_time
     *
     * @return the value of live_show.start_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.start_time
     *
     * @param startTime the value for live_show.start_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.end_time
     *
     * @return the value of live_show.end_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.end_time
     *
     * @param endTime the value for live_show.end_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.content
     *
     * @return the value of live_show.content
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.content
     *
     * @param content the value for live_show.content
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.create_time
     *
     * @return the value of live_show.create_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.create_time
     *
     * @param createTime the value for live_show.create_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.modify_time
     *
     * @return the value of live_show.modify_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.modify_time
     *
     * @param modifyTime the value for live_show.modify_time
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.flag_delete
     *
     * @return the value of live_show.flag_delete
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.flag_delete
     *
     * @param flagDelete the value for live_show.flag_delete
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_show.detail
     *
     * @return the value of live_show.detail
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_show.detail
     *
     * @param detail the value for live_show.detail
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LiveShow other = (LiveShow) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
                && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
                && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
                && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()))
                && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_show
     *
     * @mbggenerated Thu Oct 12 20:56:42 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        return result;
    }
}