package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class MapManage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.id
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.name
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.image_url
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.sort
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.is_default
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.create_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.modify_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_manage.flag_delete
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map_manage
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.id
     *
     * @return the value of map_manage.id
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.id
     *
     * @param id the value for map_manage.id
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.name
     *
     * @return the value of map_manage.name
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.name
     *
     * @param name the value for map_manage.name
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.image_url
     *
     * @return the value of map_manage.image_url
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.image_url
     *
     * @param imageUrl the value for map_manage.image_url
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.sort
     *
     * @return the value of map_manage.sort
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.sort
     *
     * @param sort the value for map_manage.sort
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.is_default
     *
     * @return the value of map_manage.is_default
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.is_default
     *
     * @param isDefault the value for map_manage.is_default
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.create_time
     *
     * @return the value of map_manage.create_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.create_time
     *
     * @param createTime the value for map_manage.create_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.modify_time
     *
     * @return the value of map_manage.modify_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.modify_time
     *
     * @param modifyTime the value for map_manage.modify_time
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_manage.flag_delete
     *
     * @return the value of map_manage.flag_delete
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_manage.flag_delete
     *
     * @param flagDelete the value for map_manage.flag_delete
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_manage
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MapManage other = (MapManage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getIsDefault() == null ? other.getIsDefault() == null : this.getIsDefault().equals(other.getIsDefault()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_manage
     *
     * @mbggenerated Sat Oct 14 22:20:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getIsDefault() == null) ? 0 : getIsDefault().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}