package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class ScenicSpot implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.name
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.icon
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.image_url
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.level
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.parent_id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.sort
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.content
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.subject
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.create_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.modify_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spot.flag_delete
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.id
     *
     * @return the value of scenic_spot.id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.id
     *
     * @param id the value for scenic_spot.id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.name
     *
     * @return the value of scenic_spot.name
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.name
     *
     * @param name the value for scenic_spot.name
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.icon
     *
     * @return the value of scenic_spot.icon
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.icon
     *
     * @param icon the value for scenic_spot.icon
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.image_url
     *
     * @return the value of scenic_spot.image_url
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.image_url
     *
     * @param imageUrl the value for scenic_spot.image_url
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.level
     *
     * @return the value of scenic_spot.level
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.level
     *
     * @param level the value for scenic_spot.level
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.parent_id
     *
     * @return the value of scenic_spot.parent_id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.parent_id
     *
     * @param parentId the value for scenic_spot.parent_id
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.sort
     *
     * @return the value of scenic_spot.sort
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.sort
     *
     * @param sort the value for scenic_spot.sort
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.content
     *
     * @return the value of scenic_spot.content
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.content
     *
     * @param content the value for scenic_spot.content
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.subject
     *
     * @return the value of scenic_spot.subject
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.subject
     *
     * @param subject the value for scenic_spot.subject
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.create_time
     *
     * @return the value of scenic_spot.create_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.create_time
     *
     * @param createTime the value for scenic_spot.create_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.modify_time
     *
     * @return the value of scenic_spot.modify_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.modify_time
     *
     * @param modifyTime the value for scenic_spot.modify_time
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spot.flag_delete
     *
     * @return the value of scenic_spot.flag_delete
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spot.flag_delete
     *
     * @param flagDelete the value for scenic_spot.flag_delete
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScenicSpot other = (ScenicSpot) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbggenerated Wed Oct 04 14:10:44 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}