package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class TbLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.user_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.table
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private String table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.data_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.flag
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.create_time
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.id
     *
     * @return the value of tb_log.id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.id
     *
     * @param id the value for tb_log.id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.user_id
     *
     * @return the value of tb_log.user_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.user_id
     *
     * @param userId the value for tb_log.user_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.table
     *
     * @return the value of tb_log.table
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.table
     *
     * @param table the value for tb_log.table
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.data_id
     *
     * @return the value of tb_log.data_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.data_id
     *
     * @param dataId the value for tb_log.data_id
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.flag
     *
     * @return the value of tb_log.flag
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.flag
     *
     * @param flag the value for tb_log.flag
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.create_time
     *
     * @return the value of tb_log.create_time
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.create_time
     *
     * @param createTime the value for tb_log.create_time
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbLog other = (TbLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTable() == null ? other.getTable() == null : this.getTable().equals(other.getTable()))
            && (this.getDataId() == null ? other.getDataId() == null : this.getDataId().equals(other.getDataId()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbggenerated Tue Oct 17 13:53:31 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTable() == null) ? 0 : getTable().hashCode());
        result = prime * result + ((getDataId() == null) ? 0 : getDataId().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}