package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class VoiceManage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.id
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.name
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.lat
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.lng
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.type
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.url
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.push_content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private String pushContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.create_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.modify_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.flag_delete
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_manage.content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.id
     *
     * @return the value of voice_manage.id
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.id
     *
     * @param id the value for voice_manage.id
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.name
     *
     * @return the value of voice_manage.name
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.name
     *
     * @param name the value for voice_manage.name
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.lat
     *
     * @return the value of voice_manage.lat
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.lat
     *
     * @param lat the value for voice_manage.lat
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.lng
     *
     * @return the value of voice_manage.lng
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.lng
     *
     * @param lng the value for voice_manage.lng
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.type
     *
     * @return the value of voice_manage.type
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.type
     *
     * @param type the value for voice_manage.type
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.url
     *
     * @return the value of voice_manage.url
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.url
     *
     * @param url the value for voice_manage.url
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.push_content
     *
     * @return the value of voice_manage.push_content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public String getPushContent() {
        return pushContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.push_content
     *
     * @param pushContent the value for voice_manage.push_content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setPushContent(String pushContent) {
        this.pushContent = pushContent == null ? null : pushContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.create_time
     *
     * @return the value of voice_manage.create_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.create_time
     *
     * @param createTime the value for voice_manage.create_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.modify_time
     *
     * @return the value of voice_manage.modify_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.modify_time
     *
     * @param modifyTime the value for voice_manage.modify_time
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.flag_delete
     *
     * @return the value of voice_manage.flag_delete
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.flag_delete
     *
     * @param flagDelete the value for voice_manage.flag_delete
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_manage.content
     *
     * @return the value of voice_manage.content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_manage.content
     *
     * @param content the value for voice_manage.content
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoiceManage other = (VoiceManage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
                && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()))
                && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
                && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
                && (this.getPushContent() == null ? other.getPushContent() == null : this.getPushContent().equals(other.getPushContent()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
                && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_manage
     *
     * @mbggenerated Fri Oct 13 16:59:36 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getPushContent() == null) ? 0 : getPushContent().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}