package com.tms.business.domain;

import java.io.Serializable;
import java.util.Date;

public class WonderfulPhoto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.id
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.image_url
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.type
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.content
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.approve
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private String approve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.create_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.modify_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wonderful_photo.flag_delete
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wonderful_photo
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.id
     *
     * @return the value of wonderful_photo.id
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.id
     *
     * @param id the value for wonderful_photo.id
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.image_url
     *
     * @return the value of wonderful_photo.image_url
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.image_url
     *
     * @param imageUrl the value for wonderful_photo.image_url
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.type
     *
     * @return the value of wonderful_photo.type
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.type
     *
     * @param type the value for wonderful_photo.type
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.content
     *
     * @return the value of wonderful_photo.content
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.content
     *
     * @param content the value for wonderful_photo.content
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.approve
     *
     * @return the value of wonderful_photo.approve
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public String getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.approve
     *
     * @param approve the value for wonderful_photo.approve
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setApprove(String approve) {
        this.approve = approve == null ? null : approve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.create_time
     *
     * @return the value of wonderful_photo.create_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.create_time
     *
     * @param createTime the value for wonderful_photo.create_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.modify_time
     *
     * @return the value of wonderful_photo.modify_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.modify_time
     *
     * @param modifyTime the value for wonderful_photo.modify_time
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wonderful_photo.flag_delete
     *
     * @return the value of wonderful_photo.flag_delete
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wonderful_photo.flag_delete
     *
     * @param flagDelete the value for wonderful_photo.flag_delete
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wonderful_photo
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WonderfulPhoto other = (WonderfulPhoto) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
                && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getApprove() == null ? other.getApprove() == null : this.getApprove().equals(other.getApprove()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
                && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wonderful_photo
     *
     * @mbggenerated Sat Oct 14 21:31:39 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getApprove() == null) ? 0 : getApprove().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}